// Sample project data
export const projects = [
  {
    id: "1",
    name: "Urban Development Analysis",
    description: "Tracking city growth patterns over 10 years",
    thumbnail: "/urban-grid.png",
    lastCommit: "Updated building footprints",
    badges: ["vector", "raster"],
    lastModified: "2 hours ago",
    contributors: [
      { name: "Alex Kim", avatar: "/ak-symbol.png" },
      { name: "Jamie Smith", avatar: "/javascript-code.png" },
    ],
    status: "active",
    progress: 75,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/light-v11",
      datasets: [
        {
          id: "buildings",
          name: "Building Footprints",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "modified",
          versions: ["v1.2", "v1.1", "v1.0"],
        },
        {
          id: "satellite",
          name: "Satellite Imagery 2023",
          visible: true,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:3857",
          status: "unchanged",
          versions: ["v2.0", "v1.0"],
        },
        {
          id: "roads",
          name: "Road Network",
          visible: true,
          type: "vector",
          format: "Shapefile",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "Updated building footprints",
          author: "Alex Kim",
          timestamp: "2h ago",
          date: "Apr 30, 2023",
          isLlm: false,
        },
        {
          id: "c2",
          message: "LLM processed height data",
          author: "GeoLLM",
          timestamp: "Yesterday",
          date: "Apr 29, 2023",
          isLlm: true,
        },
      ],
    },
  },
  {
    id: "2",
    name: "Forest Coverage Study",
    description: "Monitoring deforestation in Amazon rainforest",
    thumbnail: "/forest-coverage.png",
    lastCommit: "Added 2023 satellite imagery",
    badges: ["raster"],
    lastModified: "Yesterday",
    contributors: [
      { name: "Alex Kim", avatar: "/ak-symbol.png" },
      { name: "Taylor Wong", avatar: "/abstract-geometric-pattern.png" },
    ],
    status: "active",
    progress: 45,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/satellite-streets-v12",
      datasets: [
        {
          id: "forest",
          name: "Forest Coverage",
          visible: true,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "deforestation",
          name: "Deforestation Areas",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "modified",
          versions: ["v1.1", "v1.0"],
        },
        {
          id: "rivers",
          name: "River Network",
          visible: false,
          type: "vector",
          format: "Shapefile",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "Added 2023 satellite imagery",
          author: "Taylor Wong",
          timestamp: "Yesterday",
          date: "Apr 30, 2023",
          isLlm: false,
        },
        {
          id: "c2",
          message: "Updated deforestation boundaries",
          author: "Alex Kim",
          timestamp: "3d ago",
          date: "Apr 27, 2023",
          isLlm: false,
        },
      ],
    },
  },
  {
    id: "3",
    name: "Flood Risk Assessment",
    description: "Analyzing flood zones in coastal regions",
    thumbnail: "/coastal-flood-vulnerability.png",
    lastCommit: "LLM processed elevation data",
    badges: ["vector", "raster", "LLM"],
    lastModified: "3 days ago",
    contributors: [
      { name: "Jamie Smith", avatar: "/javascript-code.png" },
      { name: "Morgan Lee", avatar: "/machine-learning-concept.png" },
    ],
    status: "active",
    progress: 60,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/dark-v11",
      datasets: [
        {
          id: "elevation",
          name: "Elevation Model",
          visible: true,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:3857",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "flood-zones",
          name: "Flood Risk Zones",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "modified",
          versions: ["v1.2", "v1.1", "v1.0"],
        },
        {
          id: "infrastructure",
          name: "Critical Infrastructure",
          visible: true,
          type: "vector",
          format: "Shapefile",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "LLM processed elevation data",
          author: "GeoLLM",
          timestamp: "3d ago",
          date: "Apr 27, 2023",
          isLlm: true,
        },
        {
          id: "c2",
          message: "Added critical infrastructure layer",
          author: "Jamie Smith",
          timestamp: "5d ago",
          date: "Apr 25, 2023",
          isLlm: false,
        },
      ],
    },
  },
  {
    id: "4",
    name: "Transportation Network",
    description: "Public transit routes and infrastructure",
    thumbnail: "/interconnected-transit.png",
    lastCommit: "Updated bus routes",
    badges: ["vector"],
    lastModified: "1 week ago",
    contributors: [{ name: "Taylor Wong", avatar: "/abstract-geometric-pattern.png" }],
    status: "completed",
    progress: 100,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/streets-v12",
      datasets: [
        {
          id: "bus-routes",
          name: "Bus Routes",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "modified",
          versions: ["v2.0", "v1.0"],
        },
        {
          id: "subway",
          name: "Subway Lines",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "stations",
          name: "Transit Stations",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "Updated bus routes",
          author: "Taylor Wong",
          timestamp: "1w ago",
          date: "Apr 23, 2023",
          isLlm: false,
        },
        {
          id: "c2",
          message: "Added new subway stations",
          author: "Taylor Wong",
          timestamp: "2w ago",
          date: "Apr 16, 2023",
          isLlm: false,
        },
      ],
    },
  },
  {
    id: "5",
    name: "Agricultural Land Use",
    description: "Crop rotation and land use patterns",
    thumbnail: "/global-agricultural-land.png",
    lastCommit: "LLM classified crop types",
    badges: ["vector", "raster", "LLM"],
    lastModified: "2 weeks ago",
    contributors: [
      { name: "Alex Kim", avatar: "/ak-symbol.png" },
      { name: "Jamie Smith", avatar: "/javascript-code.png" },
      { name: "Morgan Lee", avatar: "/machine-learning-concept.png" },
    ],
    status: "paused",
    progress: 35,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/satellite-v9",
      datasets: [
        {
          id: "crops",
          name: "Crop Types",
          visible: true,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "modified",
          versions: ["v1.0"],
        },
        {
          id: "soil",
          name: "Soil Quality",
          visible: false,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:3857",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "irrigation",
          name: "Irrigation Systems",
          visible: true,
          type: "vector",
          format: "Shapefile",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "LLM classified crop types",
          author: "GeoLLM",
          timestamp: "2w ago",
          date: "Apr 16, 2023",
          isLlm: true,
        },
        {
          id: "c2",
          message: "Added irrigation data",
          author: "Morgan Lee",
          timestamp: "3w ago",
          date: "Apr 9, 2023",
          isLlm: false,
        },
      ],
    },
  },
  {
    id: "6",
    name: "Climate Change Impact",
    description: "Temperature and precipitation changes",
    thumbnail: "/global-temperature-trends.png",
    lastCommit: "Added 2023 temperature data",
    badges: ["raster"],
    lastModified: "1 month ago",
    contributors: [{ name: "Morgan Lee", avatar: "/machine-learning-concept.png" }],
    status: "archived",
    progress: 100,
    mapData: {
      initialCenter: [70, 30], // Pakistan
      initialZoom: 5.5,
      style: "mapbox://styles/mapbox/dark-v11",
      datasets: [
        {
          id: "temperature",
          name: "Temperature Changes",
          visible: true,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:3857",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "precipitation",
          name: "Precipitation Patterns",
          visible: true,
          type: "raster",
          format: "GeoTIFF",
          crs: "EPSG:3857",
          status: "unchanged",
          versions: ["v1.0"],
        },
        {
          id: "sea-level",
          name: "Sea Level Rise Projections",
          visible: false,
          type: "vector",
          format: "GeoJSON",
          crs: "EPSG:4326",
          status: "unchanged",
          versions: ["v1.0"],
        },
      ],
      commits: [
        {
          id: "c1",
          message: "Added 2023 temperature data",
          author: "Morgan Lee",
          timestamp: "1mo ago",
          date: "Mar 30, 2023",
          isLlm: false,
        },
        {
          id: "c2",
          message: "Updated sea level projections",
          author: "Morgan Lee",
          timestamp: "2mo ago",
          date: "Feb 28, 2023",
          isLlm: false,
        },
      ],
    },
  },
]

// Function to get a project by ID
export function getProjectById(id: string) {
  return projects.find((project) => project.id === id) || null
}
